### ISSUE TITLE
Can't Parse Multiple ISA or Envelopes in a single file

### ISSUE THREAD

**Issue by praveencbe0** [DonZoeggerle/ediFabric#21] opened 2016-02-08 21:09 UTC
Hi,

We are using EdiFabric for some time now and very much satisfied with it but recently we had received a file, which has multiple Isa or envelope segments in the file, with different component  or element separator which I have attached below.

[B57A45D689B831FA4468 - Copy.txt](https://github.com/DonZoeggerle/ediFabric/files/122179/B57A45D689B831FA4468.-.Copy.txt)

I am not able to parse the file, Exception is thrown as 'Can't parse GS Segment'
Tried both Interchange and EdiStream to convert but both fails.

This is an **valid EDI file**, which parses correctly on EDI Notepad.

I saw you have only one Interchange model which has a single ISA and IEA with list of groups.

I think the system should have an another class where we should have List of Interchange to parse multiple ISA or Envelopes one by one rather than doing it all in one shot. Then we will have a list of Interchange Models which can still have different component or element separator with its own list of groups.

Or you may have another solution to parse it. If so please respond as soon as possible.

Thanks.

**Comment by DonZoeggerle** [comment] 2016-02-22 11:35
Hi, 
You are correct - this is currently not supported by the framework. I'll add it to the list of next features.
For the time being you should manually split the envelopes by the ISA segments.

**Comment by DonZoeggerle** [comment] 2016-03-09 21:53
Closing as this is by design.

**Closed by DonZoeggerle** 2016-03-09 21:53 UTC
