### ISSUE TITLE
Interchange.LoadFrom() method returns exception value not found

### ISSUE THREAD

**Issue by tarekselem** [DonZoeggerle/ediFabric#7] opened 2015-09-02 12:30 UTC
While loading EDI file  returns the following exception :
An unhandled exception of type 'System.ArgumentNullException' occurred in EdiFabric.Framework.dll

Additional information: Value cannot be null.

**Comment by DonZoeggerle** [comment] 2015-09-07 19:25
Can you give more details ? Perhaps the stream is null ?

**Comment by DonZoeggerle** [comment] 2015-09-12 21:01
Closing as not enough information\can't reproduce.

**Closed by DonZoeggerle** 2015-09-12 21:01 UTC
