### ISSUE TITLE
Parsing a Large Document

### ISSUE THREAD

**Issue by bhyatm** [DonZoeggerle/ediFabric#65] opened 2017-05-18 23:46 UTC
Hi,

I purchased the classes for the EDI 834 Document from your site - version 005010

and it works fine, except when i do a large EDI Document i get back a message "Too many data elements in segment" 

Is there a limit to the number of segments you allow when parsing a document and how can you overcome this limitation 

Thanks

Mac

**Comment by DonZoeggerle** [comment] 2017-05-19 09:46
The message has nothing to do with the input file being too large. You can inspect the context for the exact line that is causing the issue and handcraft a separate file containing the offending message only - it will be the same result.
The error means that there are too many data elements in the segment line, e.g. as compared to the spec class.
For example if the spec for segment XYZ consists of 3 data elements: DE_1, DE_2 and DE_3, this would be a valid segment:
XYZ*1*2*3~
however in your case, your segment looks like this:
XYZ*1*2*3*4~
and the parser complains that there is a fourth element '4', which it doesn't know to which property in the class to apply it to as there are only 3.
This is a data issue and not a bug so I'm closing it.

**Closed by DonZoeggerle** 2017-05-19 09:46 UTC
